name: Build & Push Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push_image:
    name: Build and Push Image
    uses: zooniverse/ci-cd/.github/workflows/build_and_push_image.yaml@main
    with:
      repo_name: downscaler
      commit_id: ${{ github.sha }}
      latest: true