apiVersion: batch/v1
kind: CronJob
metadata:
  name: downscale-panoptes-staging-dumpworkers-job
spec:
  # Every two minutes for testing
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: downscaler-staging
        spec:
          containers:
          - name: downscaler-staging
            image: ghcr.io/zooniverse/downscaler:latest
            command: ["/bin/bash"]
            args: ["-c", "ruby downscale.rb"]
            env:
            - name: DEPLOYMENT_NAME
              value: panoptes-staging-sidekiq-dumpworker
            - name: REDIS_URL
              value: redis://panoptes-staging-redis:6379/0
            - name: MINIMUM_PODS
              value: '0'
            volumeMounts:
            - name: kubectl-config
              mountPath: "/root/.kube"
              readOnly: true
          volumes:
          - name: kubectl-config
            secret:
              secretName: downscaler-kubeconfig
              items:
              - key: kubeconfig
                path: config
          restartPolicy: Never
